[[targets]]
  hosts = ['wbs-van58-01.nie.axione.fr']
  [targets.tags]
     plaque = 'nie'
     equip = 'wbs'
     target = 'wbs-van58-01'

[[targets]]
  hosts = ['wbs-vlc58-01.nie.axione.fr']
  [targets.tags]
     plaque = 'nie'
     equip = 'wbs'
     target = 'wbs-vlc58-01'

[[targets]]
  hosts = ['wbs-bth27-02.enn.axione.fr']
  [targets.tags]
     plaque = 'enn'
     equip = 'wbs'
     target = 'wbs-bth27-02'

[[targets]]
  hosts = ['wbs-tou58-01.nie.axione.fr']
  [targets.tags]
     plaque = 'nie'
     equip = 'wbs'
     target = 'wbs-tou58-01'
