version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: infpyng_influxdb
    ports:
      - '8086:8086'
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    env_file:
      - ./grafana-provisioning/config.monitoring

  chronograf:
    image: chronograf:latest
    container_name: infpyng_chronograf
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086

  grafana:
    image: grafana/grafana:6.7.3
    container_name: infpyng_grafana
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    env_file:
      - ./grafana-provisioning/config.monitoring

  infpyng:
    image: oijkn/infpyng:latest
    container_name: infpyng_infpyng
    hostname: infpyng
    depends_on:
      - influxdb
    volumes:
      - ../config/:/infpyng/config/
      - ./data/infpyng.log:/infpyng/infpyng.log
    network_mode: host
    restart: unless-stopped
