[[targets]]
  hosts = ['lte-cor21-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-cor21-01'

[[targets]]
  hosts = ['lte-bux71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-bux71-01'

[[targets]]
  hosts = ['lte-dam71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-dam71-01'

[[targets]]
  hosts = ['lte-tou71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-tou71-01'

[[targets]]
  hosts = ['lte-msv71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-msv71-01'

[[targets]]
  hosts = ['lte-per89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-per89-01'

[[targets]]
  hosts = ['lte-vol89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-vol89-01'

[[targets]]
  hosts = ['lte-scl89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-scl89-01'

[[targets]]
  hosts = ['lte-pif89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-pif89-01'

[[targets]]
  hosts = ['lte-par89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-par89-01'

[[targets]]
  hosts = ['lte-che71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-che71-01'

[[targets]]
  hosts = ['lte-tre89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-tre89-01'

[[targets]]
  hosts = ['lte-sai89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sai89-01'

[[targets]]
  hosts = ['lte-con71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-con71-01'

[[targets]]
  hosts = ['lte-plm71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-plm71-01'

[[targets]]
  hosts = ['lte-gru71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-gru71-01'

[[targets]]
  hosts = ['lte-sfo71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sfo71-01'

[[targets]]
  hosts = ['lte-dig71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-dig71-01'

[[targets]]
  hosts = ['lte-mol89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-mol89-01'

[[targets]]
  hosts = ['lte-cui71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-cui71-01'

[[targets]]
  hosts = ['lte-sor71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sor71-01'

[[targets]]
  hosts = ['lte-mtl89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-mtl89-01'

[[targets]]
  hosts = ['lte-sry89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sry89-01'

[[targets]]
  hosts = ['lte-mlc71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-mlc71-01'

[[targets]]
  hosts = ['lte-smr89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-smr89-01'

[[targets]]
  hosts = ['lte-pui21-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-pui21-01'

[[targets]]
  hosts = ['lte-rou21-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-rou21-01'

[[targets]]
  hosts = ['lte-vld89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-vld89-01'

[[targets]]
  hosts = ['lte-cle89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-cle89-01'

[[targets]]
  hosts = ['lte-slb89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-slb89-01'

[[targets]]
  hosts = ['lte-lcr71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-lcr71-01'

[[targets]]
  hosts = ['lte-ann89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-ann89-01'

[[targets]]
  hosts = ['lte-fle71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-fle71-01'

[[targets]]
  hosts = ['lte-mou89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-mou89-01'

[[targets]]
  hosts = ['lte-sco89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sco89-01'

[[targets]]
  hosts = ['lte-tha89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-tha89-01'

[[targets]]
  hosts = ['lte-sar89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sar89-01'

[[targets]]
  hosts = ['lte-ger71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-ger71-01'

[[targets]]
  hosts = ['lte-nav71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-nav71-01'

[[targets]]
  hosts = ['lte-val89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-val89-01'

[[targets]]
  hosts = ['lte-smo89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-smo89-01'

[[targets]]
  hosts = ['lte-sfl89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-sfl89-01'

[[targets]]
  hosts = ['lte-lta71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-lta71-01'

[[targets]]
  hosts = ['lte-chi89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-chi89-01'

[[targets]]
  hosts = ['lte-pss89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-pss89-01'

[[targets]]
  hosts = ['lte-mer89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-mer89-01'

[[targets]]
  hosts = ['lte-oua89-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-oua89-01'

[[targets]]
  hosts = ['lte-cha71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-cha71-01'

[[targets]]
  hosts = ['lte-iss71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-iss71-01'

[[targets]]
  hosts = ['lte-asc71-01.bou.axione.fr']
  [targets.tags]
     plaque = 'bou'
     equip = 'lte'
     target = 'lte-asc71-01'

